from __future__ import annotations
import json
from datetime import datetime
import geopandas as gpd
import pandas as pd
from shapely.geometry import LineString

def _as_jst(series):
    return pd.to_datetime(series,errors="coerce",utc=True).dt.tz_convert("Asia/Tokyo")

def write_map(root,segs,data,events,points,cfg):
    dd=root/"docs"/"data";dd.mkdir(parents=True,exist_ok=True);cut=pd.Timestamp(cfg["baseline_cutoff"]);base=data[data.entered_at<cut];st=base.groupby("segment_id").agg(visits=("segment_id","size"),captures=("habu_capture","sum"),individuals=("habu_individuals","sum")).reset_index();m=segs.merge(st,on="segment_id",how="left").fillna({"visits":0,"captures":0,"individuals":0});gr=(m.captures.sum()+1)/(m.visits.sum()+100);m["risk"]=(m.captures+gr*20)/(m.visits+20);m["unvisited"]=(m.visits==0).astype(int);m.to_crs("EPSG:4326").to_file(dd/"segments.geojson",driver="GeoJSON")
    if not events.empty:
        ev=events.dropna(subset=["lat","lon"]).copy();ev["is_holdout"]=(_as_jst(ev.timestamp)>=cut).fillna(False).astype(int);ev["is_large_habu"]=((ev.species=="ハブ")&(ev["size"]=="大")).astype(int);gpd.GeoDataFrame(ev,geometry=gpd.points_from_xy(ev.lon,ev.lat),crs="EPSG:4326").to_file(dd/"events.geojson",driver="GeoJSON")
    latest=points[_as_jst(points.timestamp)>=pd.Timestamp(cfg["holdout_start"])].sort_values(["session_file","seq"]) if not points.empty else pd.DataFrame();lines=[]
    for s,g in latest.groupby("session_file") if not latest.empty else []:
        coords=list(zip(g.lon.astype(float),g.lat.astype(float)))
        if len(coords)>1:lines.append({"session_file":s,"geometry":LineString(coords)})
    if lines:gpd.GeoDataFrame(lines,crs="EPSG:4326").to_file(dd/"latest_route.geojson",driver="GeoJSON")
    html='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>habuAI</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#map{height:100%;margin:0}#p{position:absolute;z-index:999;background:white;padding:8px;top:8px;right:8px;border-radius:8px}</style><div id="map"></div><div id="p"><b>habuAI 瀬戸内町 10m risk</b><br>OSM 10m × 探索量補正</div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const m=L.map('map').setView([28.17,129.36],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors'}).addTo(m);Promise.all([fetch('data/segments.geojson').then(r=>r.json()),fetch('data/events.geojson').then(r=>r.ok?r.json():null),fetch('data/latest_route.geojson').then(r=>r.ok?r.json():null)]).then(([s,e,r])=>{const a=L.geoJSON(s,{style:f=>({color:(f.properties.visits||0)?((f.properties.risk||0)>.04?'#a00':(f.properties.risk||0)>.02?'#f60':'#6a6'):'#aaa',weight:f.properties.unvisited?1:4,opacity:f.properties.unvisited?.25:.8}),onEachFeature:(f,l)=>l.bindPopup(`ID ${f.properties.segment_id}<br>通過 ${f.properties.visits}<br>捕獲 ${f.properties.captures}<br>risk ${(f.properties.risk||0).toFixed(4)}`)}).addTo(m);const o={'10m risk':a};if(e)o.events=L.geoJSON(e,{pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:f.properties.species==='ハブ'?(f.properties.is_large_habu?8:6):3,fillOpacity:.75})}).addTo(m);if(r)o['latest GPX']=L.geoJSON(r,{style:{weight:4}}).addTo(m);L.control.layers(null,o,{collapsed:false}).addTo(m)});</script>''';(root/"docs"/"index.html").write_text(html,encoding="utf-8")

def write_qa(root,pipeline,cfg,points,raw,events,data,removed,strict):
    cut=pd.Timestamp(cfg["baseline_cutoff"]);event_ts=_as_jst(events.timestamp);b=events[event_ts<cut];h=b[(b.species=="ハブ")&(b.event_type=="捕獲")];ma=h[h.segment_id.notna()];un=h[h.segment_id.isna()];tr=data[data.entered_at<cut]
    weather=["rain_1h_mm","rain_3h_mm","rain_6h_mm","rain_12h_mm","rain_24h_mm","rain_48h_mm","temperature_c","humidity_pct","dew_point_c","hours_since_rain"];terrain=["elevation_m","slope_observed_deg","local_relief_proxy_m","curvature_deg","junction_distance_m","stream_distance_m","coast_distance_m","forest_distance_m","farmland_distance_m","residential_distance_m"];bio=[c for c in data if c.startswith("bio_") and ("_count" in c or "nearest_m" in c)];comp=lambda cols:{"present":[c for c in cols if c in data],"missing":[c for c in cols if c not in data],"missing_rate":{c:float(data[c].isna().mean()) for c in cols if c in data}}
    unmatched=[]
    for r in un.itertuples():
        d=getattr(r,"event_match_distance_m",None)
        unmatched.append({"timestamp":str(r.timestamp),"lat":None if pd.isna(r.lat) else float(r.lat),"lon":None if pd.isna(r.lon) else float(r.lon),"nearest_osm_distance_m":None if pd.isna(d) else float(d),"reason":getattr(r,"unmatched_reason","") or "unmatched"})
    q={"status":"ok","generated_at":datetime.now(pipeline.JST).isoformat(),"gpx_sessions":int(points.session_file.nunique()),"gpx_points":len(points),"raw_event_rows":len(raw),"deduplicated_event_rows":len(events),"duplicates_removed":removed,"baseline_main_capture_events":len(h),"baseline_main_individuals":int(pd.to_numeric(h.individual_count,errors="coerce").fillna(1).sum()),"baseline_matched_capture_events":len(ma),"baseline_matched_individuals":int(pd.to_numeric(ma.individual_count,errors="coerce").fillna(1).sum()),"baseline_unmatched_capture_events":len(un),"baseline_unmatched_individuals":int(pd.to_numeric(un.individual_count,errors="coerce").fillna(1).sum()),"unmatched":unmatched,"learning_rows_baseline":len(tr),"positive_rows_baseline":int(tr.habu_capture.sum()),"zero_rows_baseline":int((tr.habu_capture==0).sum()),"unique_visited_segments_baseline":int(tr.segment_id.nunique()),"feature_completeness":{"time":comp(["hour","sin_hour","cos_hour","segment_prior_visits"]),"weather":comp(weather),"bio_time_distance":comp(bio),"terrain":comp(terrain)},"foundation_steps":{"1_zero_data":"complete" if len(tr) and (tr.habu_capture==0).any() else "incomplete","3_exposure_corrected_time":"complete","4_weather_join":"complete" if all(c in data for c in weather) else "incomplete","5_bio_time_and_distance":"complete" if bio else "incomplete","6_terrain_features":"complete" if all(c in data for c in ["slope_observed_deg","junction_distance_m","stream_distance_m","forest_distance_m","residential_distance_m"]) else "partial","7_prediction_actual_scoring":"complete" if strict.get("status")=="ok" else "incomplete"},"strict_holdout":strict,"note":"Canonical captures without GPS remain intentionally unmatched; distant forced matches are prohibited."};(root/"reports"/"qa_summary.json").write_text(json.dumps(q,ensure_ascii=False,indent=2),encoding="utf-8");return q
